In [1]:
import pandas as  pd
import numpy as np

In [2]:
date = pd.read_csv(
    r"C:\Users\Acer\OneDrive\Desktop\Machine Learning\CSV\orders.csv")
time = pd.read_csv(
    r"C:\Users\Acer\OneDrive\Desktop\Machine Learning\CSV\messages.csv")

In [3]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [4]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [5]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [6]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

## Working with date

In [7]:
date['date'] = pd.to_datetime(date['date'])

In [8]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

In [11]:
#Extract year
date['date_year'] = date['date'].dt.year
date.head()

        date  product_id  city_id  orders  date_year
0 2019-12-10        5628       25       3       2019
1 2018-08-15        3646       14     157       2018
2 2018-10-23        1859       25       1       2018
3 2019-08-17        7292       25       1       2019
4 2019-01-06        4344       25       3       2019

In [12]:
# Extract days
date['date_day'] = date['date'].dt.day
date.head()

        date  product_id  city_id  orders  date_year  date_day
0 2019-12-10        5628       25       3       2019        10
1 2018-08-15        3646       14     157       2018        15
2 2018-10-23        1859       25       1       2018        23
3 2019-08-17        7292       25       1       2019        17
4 2019-01-06        4344       25       3       2019         6

In [13]:
#day name
date['date_day_name'] = date['date'].dt.day_name()
date.head()

        date  product_id  city_id  orders  date_year  date_day date_day_name
0 2019-12-10        5628       25       3       2019        10       Tuesday
1 2018-08-15        3646       14     157       2018        15     Wednesday
2 2018-10-23        1859       25       1       2018        23       Tuesday
3 2019-08-17        7292       25       1       2019        17      Saturday
4 2019-01-06        4344       25       3       2019         6        Sunday

In [ ]:
# Is weekend or not!!

date['date_is_weekend'] = np.where(date['date_day_name'].isin(['Saturday' , 'Sunday']) , 1 , 0)

date.drop(columns=['product_id' ,'city_id' , 'orders']).head()

        date  date_year  date_day date_day_name  date_is_weekend
0 2019-12-10       2019        10       Tuesday                0
1 2018-08-15       2018        15     Wednesday                0
2 2018-10-23       2018        23       Tuesday                0
3 2019-08-17       2019        17      Saturday                1
4 2019-01-06       2019         6        Sunday                1

In [17]:
# Extract week
date['date_week_no'] = date['date'].dt.weekday
date.head()

,date,product_id,city_id,orders,date_year,date_day,date_day_name,date_is_weekend,date_week_no
0,2019-12-10,5628,25,3,2019,10,Tuesday,0,1
1,2018-08-15,3646,14,157,2018,15,Wednesday,0,2
2,2018-10-23,1859,25,1,2018,23,Tuesday,0,1
3,2019-08-17,7292,25,1,2019,17,Saturday,1,5
4,2019-01-06,4344,25,3,2019,6,Sunday,1,6

In [18]:
# Extract quarter
date['date_quarter'] = date['date'].dt.quarter
date.head()

,date,product_id,city_id,orders,date_year,date_day,date_day_name,date_is_weekend,date_week_no,date_quarter
0,2019-12-10,5628,25,3,2019,10,Tuesday,0,1,4
1,2018-08-15,3646,14,157,2018,15,Wednesday,0,2,3
2,2018-10-23,1859,25,1,2018,23,Tuesday,0,1,4
3,2019-08-17,7292,25,1,2019,17,Saturday,1,5,3
4,2019-01-06,4344,25,3,2019,6,Sunday,1,6,1

In [19]:
# Extract semester
date["date_semester"] = np.where(date['date_quarter'].isin([1,2]) , 1 , 2)
date.head()

,date,product_id,city_id,orders,date_year,date_day,date_day_name,date_is_weekend,date_week_no,date_quarter,date_semester
0,2019-12-10,5628,25,3,2019,10,Tuesday,0,1,4,2
1,2018-08-15,3646,14,157,2018,15,Wednesday,0,2,3,2
2,2018-10-23,1859,25,1,2018,23,Tuesday,0,1,4,2
3,2019-08-17,7292,25,1,2019,17,Saturday,1,5,3,2
4,2019-01-06,4344,25,3,2019,6,Sunday,1,6,1,1

In [20]:
# Times difference with today dates
import datetime
today = datetime.datetime.today()
today

datetime.datetime(2025, 10, 5, 20, 45, 45, 777572)

In [21]:
today - date['date']

0     2126 days 20:45:45.777572
1     2608 days 20:45:45.777572
2     2539 days 20:45:45.777572
3     2241 days 20:45:45.777572
4     2464 days 20:45:45.777572
                 ...
995   2554 days 20:45:45.777572
996   2495 days 20:45:45.777572
997   2343 days 20:45:45.777572
998   2408 days 20:45:45.777572
999   2182 days 20:45:45.777572
Name: date, Length: 1000, dtype: timedelta64[ns]

In [ ]:
# week passed
np.round((today - date['date'])/np.timedelta64(1 , 'W'), 0)

0      304.0
1      373.0
2      363.0
3      320.0
4      352.0
       ...
995    365.0
996    357.0
997    335.0
998    344.0
999    312.0
Name: date, Length: 1000, dtype: float64

In [26]:
time

                    date                                                msg
0    2013-12-15 00:50:00                           ищу на сегодня мужика 37
1    2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2    2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3    2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4    2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше
..                   ...                                                ...
995  2012-03-16 00:50:00     ПАРЕНЬ СДЕЛАЕТ  МАССАЖ ЖЕНЩИНАМ -066-877-32-44
996  2014-01-23 23:14:00            сельский п 23 ищу девушку для отношений
997  2012-10-15 23:37:00  Д+Д ДЛЯ серьезных отношений. Мой номер 093-156...
998  2012-06-21 23:34:00  7 ДНЕПР М.34 ПОЗ.С Д/Ж ДЛЯ ВСТРЕЧ.Т.098 809 15 14
999  2014-06-19 23:25:00          Парень поласкает девушке...  т.0662035584

[1000 rows x 2 columns]

In [27]:
time["date"] = pd.to_datetime(time["date"])

In [28]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [30]:
time['hour'] = time['date'].dt.hour
time['min'] = time['date'].dt.minute
time['second'] = time['date'].dt.second
time.head()

,date,msg,hour,min,second
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

In [32]:
time['time'] = time['date'].dt.time
time.head()

,date,msg,hour,min,second,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00