# 📌 Naive Bayes Algorithm – Complete Revision Notes

---

## 🔹 What is Naive Bayes?

**Naive Bayes** is a **supervised machine learning algorithm** based on **Bayes’ Theorem**.

It is mainly used for:

* **Classification problems**
* Especially **text classification**

> 🎯 **Main Idea:** Predict the class with the **highest probability** given the input features.

---

## 🔹 Why is it called “Naive”?

Because it assumes:

> ❗ **All features are conditionally independent given the class**

Even though this assumption is often false in real data, Naive Bayes still works surprisingly well.

---

## 🔹 Bayes’ Theorem (Core Formula ⭐⭐⭐)

[
P(C|X) = \frac{P(X|C) \cdot P(C)}{P(X)}
]

Where:

* **C** → class (label)
* **X** → input features
* **P(C|X)** → Posterior probability
* **P(X|C)** → Likelihood
* **P(C)** → Prior probability
* **P(X)** → Evidence (constant)

---

## 🔹 Naive Independence Assumption ⭐⭐

For multiple features:
[
P(X|C) = P(x_1|C) \cdot P(x_2|C) \cdot ... \cdot P(x_n|C)
]

This simplifies computation drastically.

---

## 🔹 Final Classification Rule (VERY IMPORTANT ⭐⭐⭐)

[
\hat{C} = \arg\max_C ; P(C) \prod_{i=1}^{n} P(x_i | C)
]

👉 **Choose the class with maximum posterior probability.**

---

## 🔹 Types of Naive Bayes

### 1️⃣ Gaussian Naive Bayes

Used when features are **continuous** and normally distributed.

**Likelihood formula:**
[
P(x|C) = \frac{1}{\sqrt{2\pi\sigma_C^2}} \exp\left( -\frac{(x-\mu_C)^2}{2\sigma_C^2} \right)
]

---

### 2️⃣ Multinomial Naive Bayes

Used for:

* **Text data**
* **Word counts / frequencies**

Common in:

* Spam detection
* Sentiment analysis

---

### 3️⃣ Bernoulli Naive Bayes

Used when features are:

* **Binary (0/1)**

Example:

* Word present or not present

---

## 🔹 Log Probability Trick ⭐⭐

To avoid numerical underflow:

[
\log P(C|X) = \log P(C) + \sum_{i=1}^{n} \log P(x_i|C)
]

Used in all practical implementations.

---

## 🔹 Advantages of Naive Bayes

✅ Very fast training and prediction
✅ Works well with high-dimensional data
✅ Performs well on small datasets
✅ Excellent for text classification

---

## 🔹 Disadvantages of Naive Bayes

❌ Strong independence assumption
❌ Poor performance when features are highly correlated

---

## 🔹 When to Use Naive Bayes

✔ Spam detection
✔ Sentiment analysis
✔ Document classification
✔ Medical diagnosis (baseline model)

---

## 🔹 What You DON’T Need to Remember ❌

* Proof of Bayes’ theorem
* Mathematical derivation
* Measure-theoretic probability

👉 **Final formulas + intuition are enough**.

---

## 🔹 One-Line Ultimate Summary ⭐⭐⭐

> **Naive Bayes is a probabilistic classifier that applies Bayes’ theorem with a strong independence assumption between features.**

---

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv(
    r"C:\Users\Acer\OneDrive\Desktop\Machine Learning\CSV\play_tennis.csv")

In [3]:
df

    day   outlook  temp humidity    wind play
0    D1     Sunny   Hot     High    Weak   No
1    D2     Sunny   Hot     High  Strong   No
2    D3  Overcast   Hot     High    Weak  Yes
3    D4      Rain  Mild     High    Weak  Yes
4    D5      Rain  Cool   Normal    Weak  Yes
5    D6      Rain  Cool   Normal  Strong   No
6    D7  Overcast  Cool   Normal  Strong  Yes
7    D8     Sunny  Mild     High    Weak   No
8    D9     Sunny  Cool   Normal    Weak  Yes
9   D10      Rain  Mild   Normal    Weak  Yes
10  D11     Sunny  Mild   Normal  Strong  Yes
11  D12  Overcast  Mild     High  Strong  Yes
12  D13  Overcast   Hot   Normal    Weak  Yes
13  D14      Rain  Mild     High  Strong   No

In [4]:
df = df.drop(columns = ["day"])

In [5]:
df

     outlook  temp humidity    wind play
0      Sunny   Hot     High    Weak   No
1      Sunny   Hot     High  Strong   No
2   Overcast   Hot     High    Weak  Yes
3       Rain  Mild     High    Weak  Yes
4       Rain  Cool   Normal    Weak  Yes
5       Rain  Cool   Normal  Strong   No
6   Overcast  Cool   Normal  Strong  Yes
7      Sunny  Mild     High    Weak   No
8      Sunny  Cool   Normal    Weak  Yes
9       Rain  Mild   Normal    Weak  Yes
10     Sunny  Mild   Normal  Strong  Yes
11  Overcast  Mild     High  Strong  Yes
12  Overcast   Hot   Normal    Weak  Yes
13      Rain  Mild     High  Strong   No

## In intution way

Q)) Probelm : Outlook = Sunny , Temp=Hot , Humidity=High , Wind=Weak . Predict game will played or not . 

=> Soln: 
> Pyes=  P(sunny|yes)*P(hot|yes)*P(wind|yes)
><br>
> Pno =  P(sunny|no)*P(hot|no)*P(wind|no)
> <br>
**Whose probability will high decide game is played or not**

In [7]:
#At first we will create lookup table .
pd.crosstab(df['outlook'] , df['play'])

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [8]:
Poveryes = 4/9
Prainyes = 3/9
Psunnyyes = 2/9

Poverno = 0/5
Prainno = 2/5
Psunnyno = 3/5

In [9]:
pd.crosstab(df['temp'], df['play'])

play  No  Yes
temp
Cool   1    3
Hot    2    2
Mild   2    4

In [10]:
Pcoolyes = 3/9
Photyes = 2/9
Pmildyes = 4/9

Pcoolno = 1/5
Photno = 2/5
Pmildno = 2/5

In [11]:
pd.crosstab(df['humidity'], df['play'])

play      No  Yes
humidity
High       4    3
Normal     1    6

In [12]:
Phighyes = 3/9
Pnormalyes = 6/9

Phighno = 4/5
Pnormalno = 1/5

In [13]:
pd.crosstab(df['wind'], df['play'])

play    No  Yes
wind
Strong   3    3
Weak     2    6

In [14]:
Pstronges = 3/9
Pweakyes = 6/9

strongno = 3/5
Pweakno = 2/5

In [15]:
# Probelm : Outlook = Sunny , Temp=Hot , Humidity=High , Wind=Weak . Predict game will played or not .
Pyes = Psunnyyes * Photyes * Phighyes * Pweakyes
Pno = Psunnyno * Photno * Phighno * Pweakno

In [16]:
print(Pyes)
print(Pno)

0.010973936899862823
0.07680000000000001

### SkLearn

In [17]:
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split

In [27]:
x= df.iloc[1: , :-1]
y = df.iloc[1: , -1]
test = df.iloc[0 , :-1]

In [28]:
y

1      No
2     Yes
3     Yes
4     Yes
5      No
6     Yes
7      No
8     Yes
9     Yes
10    Yes
11    Yes
12    Yes
13     No
Name: play, dtype: object

In [29]:
test

outlook     Sunny
temp          Hot
humidity     High
wind         Weak
Name: 0, dtype: object

In [30]:
x

     outlook  temp humidity    wind
1      Sunny   Hot     High  Strong
2   Overcast   Hot     High    Weak
3       Rain  Mild     High    Weak
4       Rain  Cool   Normal    Weak
5       Rain  Cool   Normal  Strong
6   Overcast  Cool   Normal  Strong
7      Sunny  Mild     High    Weak
8      Sunny  Cool   Normal    Weak
9       Rain  Mild   Normal    Weak
10     Sunny  Mild   Normal  Strong
11  Overcast  Mild     High  Strong
12  Overcast   Hot   Normal    Weak
13      Rain  Mild     High  Strong

In [32]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
from sklearn.naive_bayes import BernoulliNB
# Pipeline
model = Pipeline([
    ('ohe', OneHotEncoder(handle_unknown='ignore')),
    ('nb', BernoulliNB())
])

In [33]:
model.fit(x , y)

Pipeline(steps=[('ohe', OneHotEncoder(handle_unknown='ignore')),
                ('nb', BernoulliNB())])

In [35]:
# Convert the Series (single sample) into a single-row DataFrame
model.predict(test.to_frame().T)

array(['No'], dtype='<U3')

Game is not played